services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: bestiary
      POSTGRES_USER: bestiary
      POSTGRES_PASSWORD: bestiarypass
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bestiary_network

  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      BESTIARY_DATABASE_URL: postgres://bestiary:bestiarypass@postgres:5432/bestiary?sslmode=disable
    networks:
      - bestiary_network

volumes:
  postgres_data:

networks:
  bestiary_network:
    driver: bridge