services:
  postgres-local:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: bestiary
      POSTGRES_USER: bestiary
      POSTGRES_PASSWORD: temppass
    networks:
      - bestiary_network_local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bestiary"]
      interval: 5s
      timeout: 5s
      retries: 5

  app-local:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      postgres-local:
        condition: service_healthy
    environment:
      BESTIARY_DATABASE_URL: postgres://bestiary:temppass@postgres-local:5432/bestiary?sslmode=disable
      GIN_MODE: release
    networks:
      - bestiary_network_local

networks:
  bestiary_network_local:
    driver: bridge